---

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'gems/**/*'
    - 'node_modules/**/*'
  NewCops: disable

Bundler/OrderedGems:
  Enabled: false

Naming:
  Enabled: false

Style:
  Enabled: false

Layout:
  Enabled: false

Metrics:
  Enabled: false