# Do not change version. This is the version of aws buildspec, not the version
# of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
      ruby: 3,1
    commands:
      - echo un-customized install phase, add more install commands here...
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install gulp-cli
      - echo Updating to Ruby 3.0 via rbenv
      - rbenv install 3.0.3 && rbenv global 3.0.3
      - echo Installing Ruby dependencies...
      - gem install bundler
      - bundle install
  build:
    commands:
      - echo Build started on `date`
      - echo Linting the Node.js code
      - npx eslint .
      - echo Linting Sinatra/Ruby code with Rubocop
      - bundle exec rubocop
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it I
# will include unnecessary packages used only for building and testing.
# ExpressJS apps will need other artifact directories include
#   (bin/*, public/*, routes/*, views/* etc).
# artifacts:
#   files:
#     - app.js
#     - index.html
#     - package.json
#     - node_modules/async/*
#     - node_modules/lodash/*
