# Process compose for starting the Jschol service
version: "0.5"

processes:
  jschol:
   command: "rm .mysqlpsk.3306.* || ./gulp"
   availability:
    restart: "always"
    readiness_probe:
      http_get:
        host: 127.0.0.1
        scheme: http
        path: "/"
        port: 18880
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
