---
name: lint-jschol
on: [push, pull_request]
jobs: 
  Rubocop:
    name: Rubocop
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: gimenete/rubocop-action@1.0
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ESlint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10'
    - run: npm install
    - run: npx eslint .