---
name: lint-jschol
on: [push, pull_request]
jobs: 
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: gimenete/rubocop-action@1.0
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}