---
name: lint-jschol
on: [push, pull_request]
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  discussions: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs: 
  Rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.5
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubocop-
    - name: Install gems
      run: |
        sudo apt-get update -qq && sudo apt-get autoclean && sudo apt-get install build-essential
        bundle install --jobs 4 --retry 3
    - name: Run RuboCop
      run: bundle exec rubocop --parallel

  ESlint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10'
    - run: npm install
    - run: npx eslint .