---
name: lint-jschol
on: [push, pull_request]
permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  issues: write
  discussions: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
jobs:
  Rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: luizfonseca/github-actions-rubocop@1.5.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ESlint:
    name: ESlint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '10'
    - run: npm install
    - run: npx eslint .
